# Generated by Django 5.2.5 on 2025-08-25 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=50)),
                ('myskill', models.CharField(max_length=50)),
                ('portfolioDesc', models.CharField(max_length=500)),
                ('cvlink', models.URLField(max_length=500)),
                ('github', models.URLField()),
                ('linkedin', models.URLField(max_length=500)),
                ('myemail', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('projectlink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
                ('freelance', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('myname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile', verbose_name='Full Name')),
                ('skills', models.ManyToManyField(to='main.skill')),
            ],
        ),
    ]
