# Generated by Django 5.2.5 on 2025-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_project_skill_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectimg',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
