# Generated by Django 5.2.5 on 2025-10-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_projectimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectgithub',
            field=models.URLField(blank=True, null=True),
        ),
    ]
